esphome:
  name: bad
  platform: ESP8266
  board: nodemcu

wifi:
  <<: !include secrets.yml
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bad Fallback Hotspot"

<<: !include defaults.yml

sensor:
  - platform: dht
    pin: 4
    model: DHT22
    temperature:
      name: "Bad Temperatur"
    humidity:
      name: "Bad Luftfeuchtigkeit"
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "Bad Room Status"  
