esphome:
  name: bad
  platform: ESP8266
  board: nodemcu

wifi:
  <<: !include secrets.yml
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bad Fallback Hotspot"

sensor:
  - platform: dht
    pin: 4
    model: DHT22
    temperature:
      name: "Bad Temperatur"
    humidity:
      name: "Bad Luftfeuchtigkeit"
    update_interval: 60s
  - platform: wifi_signal
    name: "WiFi Signal Bad"

binary_sensor:
  - platform: status
    name: "Bad Room Status"  

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
