esphome:
  name: foobar
  platform: ESP32
  board: nodemcu-32s

wifi:
  <<: !include secrets.yml
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Foobar Fallback Hotspot"

captive_portal:

esp32_ble_tracker:

sensor:
  - platform: dht
    pin: 4
    model: DHT22
    temperature:
      name: "Wohnzimmer Temperatur"
    humidity:
      name: "Wohnzimmer Luftfeuchtigkeit"
    update_interval: 60s
  - platform: esp32_hall
    name: "ESP32 Hall Wohnzimmer"
    update_interval: 60s
  - platform: wifi_signal
    name: "WiFi Signal Wohnzimmer"
    update_interval: 60s
  - platform: ble_rssi
    mac_address: 08:F4:AB:C3:25:A7
    name: "Daniel Apple Watch"
  - platform: ble_rssi
    mac_address: DC:41:5F:BF:77:A6
    name: "Daniel iPhone"
  - platform: ble_rssi
    mac_address: 38:F9:D3:9B:EA:B0
    name: "Daniel Macbook"
  - platform: ble_rssi
    mac_address: E4:FD:A1:90:56:F8
    name: "Ye Huawei"
  - platform: ble_rssi
    mac_address: 80:B0:3D:D2:1F:55
    name: "Ye iPhone"

binary_sensor:
  - platform: status
    name: "Living Room Status"
  - platform: ble_presence
    mac_address: 08:F4:AB:C3:25:A7
    name: "Daniel Apple Watch"
  - platform: ble_presence
    mac_address: DC:41:5F:BF:77:A6
    name: "Daniel iPhone"
  - platform: ble_presence
    mac_address: 38:F9:D3:9B:EA:B0
    name: "Daniel Macbook"
  - platform: ble_presence
    mac_address: E4:FD:A1:90:56:F8
    name: "Ye Huawei"
  - platform: ble_presence
    mac_address: 80:B0:3D:D2:1F:55
    name: "Ye iPhone"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota: