esphome:
  name: waschkeller
  platform: ESP32
  board: nodemcu-32s

wifi:
  <<: !include secrets.yml
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Waschkeller Fallback Hotspot"

sensor:
  - platform: dht
    pin: 4
    model: DHT22
    temperature:
      name: "Waschzimmer Temperatur"
    humidity:
      name: "Waschzimmer Luftfeuchtigkeit"
    update_interval: 60s
  - platform: esp32_hall
    name: "ESP32 Hall Waschraum"
    update_interval: 60s
  - platform: wifi_signal
    name: "WiFi Signal Waschraum"

binary_sensor:
  - platform: status
    name: "Waschzimmer Room Status"  

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
