esphome:
  name: foobar
  platform: ESP32
  board: nodemcu-32s

wifi:
  <<: !include secrets.yml
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Foobar Fallback Hotspot"

<<: !include defaults.yml

esp32_ble_tracker:

sensor:
  - platform: dht
    pin: 4
    model: DHT22
    temperature:
      name: "Wohnzimmer Temperatur"
    humidity:
      name: "Wohnzimmer Luftfeuchtigkeit"
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "Living Room Status"